-- MySQL Script generated by MySQL Workbench
-- Thu Nov 10 12:13:26 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema urna
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema urna
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `urna` DEFAULT CHARACTER SET utf8 ;
USE `urna` ;

-- -----------------------------------------------------
-- Table `urna`.`Acessos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `urna`.`Acessos` (
  `AcessoID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(150) NOT NULL,
  `Usuario` VARCHAR(45) NOT NULL,
  `Senha` VARCHAR(255) NOT NULL,
  `Excluido` CHAR(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`AcessoID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `urna`.`Partidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `urna`.`Partidos` (
  `PartidoID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NOT NULL,
  `Numero` INT NOT NULL,
  `Sigla` VARCHAR(45) NOT NULL,
  `Excluido` CHAR(1) NOT NULL,
  PRIMARY KEY (`PartidoID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `urna`.`Candidatos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `urna`.`Candidatos` (
  `CandidatoID` INT NOT NULL AUTO_INCREMENT,
  `NomeCompleto` VARCHAR(100) NOT NULL,
  `Foto` VARCHAR(45) NOT NULL,
  `Numero` VARCHAR(45) NOT NULL,
  `Excluidos` CHAR(1) NOT NULL,
  `Nascimento` VARCHAR(45) NOT NULL,
  `NomeUrna` VARCHAR(100) NOT NULL,
  `Sigla` VARCHAR(45) NOT NULL,
  `Situacao` VARCHAR(45) NOT NULL,
  `ImportadorID` INT NOT NULL,
  PRIMARY KEY (`CandidatoID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `urna`.`Cargos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `urna`.`Cargos` (
  `CargoID` INT NOT NULL,
  `Nome` VARCHAR(100) NOT NULL,
  `Digitos` INT NOT NULL,
  `Vice` TINYINT NOT NULL,
  `Suplente` TINYINT NOT NULL,
  `Excluido` CHAR(1) NOT NULL,
  PRIMARY KEY (`CargoID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `urna`.`Eleitores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `urna`.`Eleitores` (
  `EleitorID` INT NOT NULL AUTO_INCREMENT,
  `Inscricao` VARCHAR(12) NOT NULL,
  `Estado` CHAR(2) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Eleitorescol` VARCHAR(45) NOT NULL,
  `Zona` CHAR(4) NOT NULL,
  `Secao` INT NOT NULL,
  `DataDeNascimento` VARCHAR(45) NOT NULL,
  `Falecido` TINYINT NOT NULL,
  `Cancelado` TINYINT NOT NULL,
  PRIMARY KEY (`EleitorID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `urna`.`Eleicoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `urna`.`Eleicoes` (
  `EleicaoID` INT NOT NULL AUTO_INCREMENT,
  `HoraInicio` TIME NOT NULL,
  `HoraFim` TIME NOT NULL,
  `Data` DATE NOT NULL,
  `Tipo` CHAR(1) NOT NULL,
  `Ano` YEAR NOT NULL,
  `Eleitores_EleitorID` INT NOT NULL,
  `Candidatos_CandidatoID` INT NOT NULL,
  PRIMARY KEY (`EleicaoID`),
  INDEX `fk_Eleicoes_Eleitores_idx` (`Eleitores_EleitorID` ASC) ,
  INDEX `fk_Eleicoes_Candidatos_idx` (`Candidatos_CandidatoID` ASC) ,
  CONSTRAINT `fk_Eleicoes_Eleitores`
    FOREIGN KEY (`Eleitores_EleitorID`)
    REFERENCES `urna`.`Eleitores` (`EleitorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Eleicoes_Candidatos1`
    FOREIGN KEY (`Candidatos_CandidatoID`)
    REFERENCES `urna`.`Candidatos` (`CandidatoID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `urna`.`EleitorVoto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `urna`.`EleitorVoto` (
  `EleitorVotoID` INT NOT NULL AUTO_INCREMENT,
  `EleitorInscricao` VARCHAR(45) NOT NULL,
  `Estado` CHAR(2) NOT NULL,
  `Secao` VARCHAR(45) NOT NULL,
  `Zona` VARCHAR(4) NOT NULL,
  `DataHota` DATETIME NOT NULL,
  `EleicaoID` INT NOT NULL,
  PRIMARY KEY (`EleitorVotoID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `urna`.`VotoCandidatos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `urna`.`VotoCandidatos` (
  `VotoCandidatosID` INT NOT NULL AUTO_INCREMENT,
  `Estado` CHAR(2) NOT NULL,
  `Secao` VARCHAR(4) NOT NULL,
  `Zona` VARCHAR(4) NOT NULL,
  `VotoPresidente` VARCHAR(2) NOT NULL,
  `VotoGovernador` VARCHAR(2) NOT NULL,
  `VotoSenador` VARCHAR(3) NOT NULL,
  `VotoDepEstadual` VARCHAR(4) NOT NULL,
  `VotoDepFedereal` VARCHAR(4) NOT NULL,
  `DataHora` DATETIME NOT NULL,
  `Importador` INT NOT NULL,
  PRIMARY KEY (`VotoCandidatosID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `urna`.`Importador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `urna`.`Importador` (
  `ImportadorID` INT NOT NULL AUTO_INCREMENT,
  `DataHora` DATETIME NOT NULL,
  `Arquivo` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ImportadorID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `urna`.`Eleitores_has_EleitorVoto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `urna`.`Eleitores_has_EleitorVoto` (
  `Eleitores_EleitorID` INT NOT NULL,
  `EleitorVoto_EleitorVotoID` INT NOT NULL,
  INDEX `fk_Eleitores_has_EleitorVoto_EleitorVoto1_idx` (`EleitorVoto_EleitorVotoID` ASC) ,
  INDEX `fk_Eleitores_has_EleitorVoto_Eleitores1_idx` (`Eleitores_EleitorID` ASC) ,
  CONSTRAINT `fk_Eleitores_has_EleitorVoto_Eleitores1`
    FOREIGN KEY (`Eleitores_EleitorID`)
    REFERENCES `urna`.`Eleitores` (`EleitorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Eleitores_has_EleitorVoto_EleitorVoto1`
    FOREIGN KEY (`EleitorVoto_EleitorVotoID`)
    REFERENCES `urna`.`EleitorVoto` (`EleitorVotoID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `urna`.`Candidatos_has_VotoCandidatos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `urna`.`Candidatos_has_VotoCandidatos` (
  `Candidatos_CandidatoID` INT NOT NULL,
  `VotoCandidatos_VotoCandidatosID` INT NOT NULL,
  INDEX `fk_Candidatos_has_VotoCandidatos_VotoCandidatos1_idx` (`VotoCandidatos_VotoCandidatosID` ASC) ,
  INDEX `fk_Candidatos_has_VotoCandidatos_Candidatos1_idx` (`Candidatos_CandidatoID` ASC) ,
  CONSTRAINT `fk_Candidatos_has_VotoCandidatos_Candidatos1`
    FOREIGN KEY (`Candidatos_CandidatoID`)
    REFERENCES `urna`.`Candidatos` (`CandidatoID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Candidatos_has_VotoCandidatos_VotoCandidatos1`
    FOREIGN KEY (`VotoCandidatos_VotoCandidatosID`)
    REFERENCES `urna`.`VotoCandidatos` (`VotoCandidatosID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `urna`.`Cargos_has_Candidatos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `urna`.`Cargos_has_Candidatos` (
  `Cargos_CargoID` INT NOT NULL,
  `Candidatos_CandidatoID` INT NOT NULL,
  INDEX `fk_Cargos_has_Candidatos_Candidatos1_idx` (`Candidatos_CandidatoID` ASC) ,
  INDEX `fk_Cargos_has_Candidatos_Cargos1_idx` (`Cargos_CargoID` ASC) ,
  CONSTRAINT `fk_Cargos_has_Candidatos_Cargos1`
    FOREIGN KEY (`Cargos_CargoID`)
    REFERENCES `urna`.`Cargos` (`CargoID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cargos_has_Candidatos_Candidatos1`
    FOREIGN KEY (`Candidatos_CandidatoID`)
    REFERENCES `urna`.`Candidatos` (`CandidatoID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `urna`.`Partidos_has_Candidatos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `urna`.`Partidos_has_Candidatos` (
  `Partidos_PartidoID` INT NOT NULL,
  `Candidatos_CandidatoID` INT NOT NULL,
  INDEX `fk_Partidos_has_Candidatos_Candidatos1_idx` (`Candidatos_CandidatoID` ASC) ,
  INDEX `fk_Partidos_has_Candidatos_Partidos1_idx` (`Partidos_PartidoID` ASC) ,
  CONSTRAINT `fk_Partidos_has_Candidatos_Partidos1`
    FOREIGN KEY (`Partidos_PartidoID`)
    REFERENCES `urna`.`Partidos` (`PartidoID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Partidos_has_Candidatos_Candidatos1`
    FOREIGN KEY (`Candidatos_CandidatoID`)
    REFERENCES `urna`.`Candidatos` (`CandidatoID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `urna`.`Cidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `urna`.`Cidades` (
  `CidadesID` INT NOT NULL AUTO_INCREMENT,
  `CodigoUF` VARCHAR(2) NOT NULL,
  `CodigoCidade` VARCHAR(7) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CidadesID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
h